// Code generated by ent, DO NOT EDIT.

package sensor

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the sensor type in the database.
	Label = "sensor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSensorID holds the string denoting the sensor_id field in the database.
	FieldSensorID = "sensor_id"
	// FieldLongitude holds the string denoting the longitude field in the database.
	FieldLongitude = "longitude"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// Table holds the table name of the sensor in the database.
	Table = "sensors"
)

// Columns holds all SQL columns for sensor fields.
var Columns = []string{
	FieldID,
	FieldSensorID,
	FieldLongitude,
	FieldLatitude,
	FieldType,
	FieldValue,
	FieldCreateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
