// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SensorsColumns holds the columns for the "sensors" table.
	SensorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "sensor_id", Type: field.TypeString},
		{Name: "temperature", Type: field.TypeFloat64},
		{Name: "electric_current", Type: field.TypeFloat64},
		{Name: "create_time", Type: field.TypeTime},
	}
	// SensorsTable holds the schema information for the "sensors" table.
	SensorsTable = &schema.Table{
		Name:       "sensors",
		Columns:    SensorsColumns,
		PrimaryKey: []*schema.Column{SensorsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sensor_sensor_id",
				Unique:  false,
				Columns: []*schema.Column{SensorsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SensorsTable,
	}
)

func init() {
}
