// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ent-timescale/ent/schema"
	"ent-timescale/ent/sensor"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sensorFields := schema.Sensor{}.Fields()
	_ = sensorFields
	// sensorDescID is the schema descriptor for id field.
	sensorDescID := sensorFields[0].Descriptor()
	// sensor.DefaultID holds the default value on creation for the id field.
	sensor.DefaultID = sensorDescID.Default.(func() uuid.UUID)
}
