// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ent-timescale/ent/predicate"
	"ent-timescale/ent/sensor"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SensorUpdate is the builder for updating Sensor entities.
type SensorUpdate struct {
	config
	hooks     []Hook
	mutation  *SensorMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SensorUpdate builder.
func (su *SensorUpdate) Where(ps ...predicate.Sensor) *SensorUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetSensorID sets the "sensor_id" field.
func (su *SensorUpdate) SetSensorID(s string) *SensorUpdate {
	su.mutation.SetSensorID(s)
	return su
}

// SetTemperature sets the "temperature" field.
func (su *SensorUpdate) SetTemperature(f float64) *SensorUpdate {
	su.mutation.ResetTemperature()
	su.mutation.SetTemperature(f)
	return su
}

// AddTemperature adds f to the "temperature" field.
func (su *SensorUpdate) AddTemperature(f float64) *SensorUpdate {
	su.mutation.AddTemperature(f)
	return su
}

// SetElectricCurrent sets the "electric_current" field.
func (su *SensorUpdate) SetElectricCurrent(f float64) *SensorUpdate {
	su.mutation.ResetElectricCurrent()
	su.mutation.SetElectricCurrent(f)
	return su
}

// AddElectricCurrent adds f to the "electric_current" field.
func (su *SensorUpdate) AddElectricCurrent(f float64) *SensorUpdate {
	su.mutation.AddElectricCurrent(f)
	return su
}

// SetCreateTime sets the "create_time" field.
func (su *SensorUpdate) SetCreateTime(t time.Time) *SensorUpdate {
	su.mutation.SetCreateTime(t)
	return su
}

// Mutation returns the SensorMutation object of the builder.
func (su *SensorUpdate) Mutation() *SensorMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SensorUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SensorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SensorUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SensorUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SensorUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (su *SensorUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SensorUpdate {
	su.modifiers = append(su.modifiers, modifiers...)
	return su
}

func (su *SensorUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sensor.Table,
			Columns: sensor.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: sensor.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.SensorID(); ok {
		_spec.SetField(sensor.FieldSensorID, field.TypeString, value)
	}
	if value, ok := su.mutation.Temperature(); ok {
		_spec.SetField(sensor.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedTemperature(); ok {
		_spec.AddField(sensor.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.ElectricCurrent(); ok {
		_spec.SetField(sensor.FieldElectricCurrent, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedElectricCurrent(); ok {
		_spec.AddField(sensor.FieldElectricCurrent, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.CreateTime(); ok {
		_spec.SetField(sensor.FieldCreateTime, field.TypeTime, value)
	}
	_spec.AddModifiers(su.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sensor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// SensorUpdateOne is the builder for updating a single Sensor entity.
type SensorUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SensorMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetSensorID sets the "sensor_id" field.
func (suo *SensorUpdateOne) SetSensorID(s string) *SensorUpdateOne {
	suo.mutation.SetSensorID(s)
	return suo
}

// SetTemperature sets the "temperature" field.
func (suo *SensorUpdateOne) SetTemperature(f float64) *SensorUpdateOne {
	suo.mutation.ResetTemperature()
	suo.mutation.SetTemperature(f)
	return suo
}

// AddTemperature adds f to the "temperature" field.
func (suo *SensorUpdateOne) AddTemperature(f float64) *SensorUpdateOne {
	suo.mutation.AddTemperature(f)
	return suo
}

// SetElectricCurrent sets the "electric_current" field.
func (suo *SensorUpdateOne) SetElectricCurrent(f float64) *SensorUpdateOne {
	suo.mutation.ResetElectricCurrent()
	suo.mutation.SetElectricCurrent(f)
	return suo
}

// AddElectricCurrent adds f to the "electric_current" field.
func (suo *SensorUpdateOne) AddElectricCurrent(f float64) *SensorUpdateOne {
	suo.mutation.AddElectricCurrent(f)
	return suo
}

// SetCreateTime sets the "create_time" field.
func (suo *SensorUpdateOne) SetCreateTime(t time.Time) *SensorUpdateOne {
	suo.mutation.SetCreateTime(t)
	return suo
}

// Mutation returns the SensorMutation object of the builder.
func (suo *SensorUpdateOne) Mutation() *SensorMutation {
	return suo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SensorUpdateOne) Select(field string, fields ...string) *SensorUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Sensor entity.
func (suo *SensorUpdateOne) Save(ctx context.Context) (*Sensor, error) {
	var (
		err  error
		node *Sensor
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SensorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, suo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Sensor)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from SensorMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SensorUpdateOne) SaveX(ctx context.Context) *Sensor {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SensorUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SensorUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (suo *SensorUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SensorUpdateOne {
	suo.modifiers = append(suo.modifiers, modifiers...)
	return suo
}

func (suo *SensorUpdateOne) sqlSave(ctx context.Context) (_node *Sensor, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sensor.Table,
			Columns: sensor.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: sensor.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sensor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sensor.FieldID)
		for _, f := range fields {
			if !sensor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sensor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.SensorID(); ok {
		_spec.SetField(sensor.FieldSensorID, field.TypeString, value)
	}
	if value, ok := suo.mutation.Temperature(); ok {
		_spec.SetField(sensor.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedTemperature(); ok {
		_spec.AddField(sensor.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.ElectricCurrent(); ok {
		_spec.SetField(sensor.FieldElectricCurrent, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedElectricCurrent(); ok {
		_spec.AddField(sensor.FieldElectricCurrent, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.CreateTime(); ok {
		_spec.SetField(sensor.FieldCreateTime, field.TypeTime, value)
	}
	_spec.AddModifiers(suo.modifiers...)
	_node = &Sensor{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sensor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
